with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName}}_mock.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}_mocks"
packages:
    github.com/ilya-mezentsev/micro-dep/store/internal/services/entity:
        interfaces:
            Repo:

    github.com/ilya-mezentsev/micro-dep/store/internal/services/endpoint:
        interfaces:
            Repo:

    github.com/ilya-mezentsev/micro-dep/store/internal/services/relation:
        interfaces:
            Repo:
