with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName}}_mock.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}_mocks"
packages:
    github.com/ilya-mezentsev/micro-dep/user/internal/services/session:
        interfaces:
            AuthorRepo:
            TokenRepo:

    github.com/ilya-mezentsev/micro-dep/user/internal/services/register:
        interfaces:
            AccountRepo:
            AuthorRepo:
